annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/control-plane-catalog/prometheus-remotewrite-0.1.4.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/control-plane-catalog/prometheus-remotewrite-0.1.4.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/control-plane-catalog/prometheus-remotewrite-0.1.4.tgz-meta/values.schema.json
  config.giantswarm.io/version: 1.x.x
chartApiVersion: v2
chartFile: prometheus-remotewrite-0.1.4.tgz
dateCreated: '2024-03-13T17:11:47.801857'
digest: 497d64b926eeb29cfe29cea5eabe0eab0f0f59ad2012bd01b968985737e590c1
home: https://github.com/giantswarm/prometheus-remotewrite-app
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
