annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/control-plane-catalog/prometheus-remotewrite-0.8.0.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/control-plane-catalog/prometheus-remotewrite-0.8.0.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/control-plane-catalog/prometheus-remotewrite-0.8.0.tgz-meta/values.schema.json
  config.giantswarm.io/version: 1.x.x
chartApiVersion: v2
chartFile: prometheus-remotewrite-0.8.0.tgz
dateCreated: '2025-03-04T13:58:46.468979Z'
digest: 9179313fd7251896f5b792c7b4ab9012e786f21fefc694e607b897a6a2ed889a
home: https://github.com/giantswarm/prometheus-remotewrite-app
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
