annotations:
  application.giantswarm.io/team: atlas
chartApiVersion: v2
chartFile: prometheus-rules-4.108.0.tgz
dateCreated: '2026-06-30T12:39:35.249110Z'
digest: 31e76682a3d94d20c3a2424153f56bdfa21908c59704420020ce6a5ff8771aa9
home: https://github.com/giantswarm/prometheus-rules
icon: https://s.giantswarm.io/app-icons/1/png/default-app-light.png
