annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/control-plane-catalog/prometheus-rules-4.15.2.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/control-plane-catalog/prometheus-rules-4.15.2.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/control-plane-catalog/prometheus-rules-4.15.2.tgz-meta/values.schema.json
  config.giantswarm.io/version: 1.x.x
chartApiVersion: v1
chartFile: prometheus-rules-4.15.2.tgz
dateCreated: '2024-09-18T08:14:26.816905'
digest: c31a9794fb5f425a993540cbac47bf46279ca78d7e7e1e5984b6d0c2c4dacac4
home: https://github.com/giantswarm/prometheus-rules
icon: https://s.giantswarm.io/app-icons/1/png/default-app-light.png
