annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/control-plane-catalog/prometheus-rules-3.7.1.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/control-plane-catalog/prometheus-rules-3.7.1.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/control-plane-catalog/prometheus-rules-3.7.1.tgz-meta/values.schema.json
  config.giantswarm.io/version: 1.x.x
chartApiVersion: v1
chartFile: prometheus-rules-3.7.1.tgz
dateCreated: '2024-04-08T09:39:39.688461'
digest: 795221a37ddfa025e38d8aefc1fb2d921267a976a29148952af403314192ccd2
home: https://github.com/giantswarm/prometheus-rules
icon: https://s.giantswarm.io/app-icons/1/png/default-app-light.png
