annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/control-plane-catalog/prometheus-remotewrite-0.2.0.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/control-plane-catalog/prometheus-remotewrite-0.2.0.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/control-plane-catalog/prometheus-remotewrite-0.2.0.tgz-meta/values.schema.json
  config.giantswarm.io/version: 1.x.x
chartApiVersion: v2
chartFile: prometheus-remotewrite-0.2.0.tgz
dateCreated: '2024-03-20T09:21:42.470162'
digest: 634b9b482f5ae7bab937826045f742c09af25d614d65acdd426d4789f325d65a
home: https://github.com/giantswarm/prometheus-remotewrite-app
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
