annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/control-plane-catalog/prometheus-operator-app-0.9.0.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/control-plane-catalog/prometheus-operator-app-0.9.0.tgz-meta/README.md
  application.giantswarm.io/values-schema: https://giantswarm.github.io/control-plane-catalog/prometheus-operator-app-0.9.0.tgz-meta/values.schema.json
  artifacthub.io/links: "- name: Chart Source\n  url: https://github.com/prometheus-community/helm-charts\n\
    - name: Upstream Project\n  url: https://github.com/prometheus-operator/kube-prometheus\n"
  artifacthub.io/operator: 'true'
  config.giantswarm.io/version: 1.x.x
chartApiVersion: v2
chartFile: prometheus-operator-app-0.9.0.tgz
dateCreated: '2021-07-14T13:06:07.548980'
digest: b14a1f8e012838bec313fb50926398d68caa06736a778e8919483e55bc570680
home: https://github.com/giantswarm/prometheus-operator-app
icon: https://s.giantswarm.io/app-icons/1/png/prometheus-operator-app-light.png
